AllCops:
  TargetRubyVersion: 2.1
  Exclude:
  - 'vendor/**/*'
  - 'experiments/**/*'

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/MutableConstant:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

MethodLength:
  Enabled: true
  Max: 20

# TODO: more re-factoring to reduce method complexity
Metrics/AbcSize:
  Max: 40
