AllCops:
  TargetRubyVersion: 2.1
  Exclude:
  - 'vendor/**/*'

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/MutableConstant:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

MethodLength:
  Enabled: true
  Max: 100

# TODO: break up into smaller classes?
ClassLength:
  Max: 200

# TODO: re-factor write_chunk and write_manifest
Metrics/AbcSize:
  Max: 55

# TODO: convert File.open block into a template?
Metrics/BlockLength:
  Max: 32
