AllCops:
  TargetRubyVersion: 2.1
  Exclude:
  - 'vendor/**/*'

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/MutableConstant:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

MethodLength:
  Enabled: true
  Max: 100
